#!/usr/bin/env bash
#
# Summary: List installed packages
# Usage: basher list

set -e

if [ "$#" -gt 0 ]; then
  basher-help list
  exit 1
fi

shopt -s nullglob

  find "$BASHER_PACKAGES_PATH" -mindepth 2 -maxdepth 2 -type d \
| while read -r package_path ; do
    package=$(basename "$package_path")
    user_folder=$(dirname "$package_path")
    username=$(basename "$user_folder")
    echo "$username/$package"
  done