#!/usr/bin/env bash
#
# Usage: basher _deps <package>
# Summary: Globally installs package runtime dependencies
#
# Installs the package dependencies, specified with the
# DEPS= variable on package.sh.
#
# Example: DEPS=username/repo1:otheruser/repo2

set -e

if [ "$#" -ne 1 ]; then
  basher-help _deps
  exit 1
fi

package="$1"
shopt -s nullglob

package_file="$BASHER_PACKAGES_PATH/$package/package.sh"
if [ -e "$package_file" ]; then
  # shellcheck disable=SC1090
  source "$package_file"
  # shellcheck disable=SC2153
  IFS=: read -r -a deps <<< "$DEPS"

  for dep in "${deps[@]}"
  do
    basher-install "$dep"
  done
else
  exit
fi


